### ISSUE TITLE
Include the rabbitmq_delayed_message_exchange by default

### ISSUE THREAD

**Issue by fancyremarker** [aptible/docker-rabbitmq#15]
cc: @krallin 

Has been manually installed via:

```
wget http://www.rabbitmq.com/community-plugins/v3.6.x/rabbitmq_delayed_message_exchange-0.0.1.ez
mv rabbitmq_delayed_message_exchange-0.0.1.ez /srv/rabbitmq_server-3.5.7/plugins/
rabbitmq-plugins enable rabbitmq_delayed_message_exchange
```

**Comment by krallin** [comment]
@fancyremarker looks like we're downloading a plugin for RabbitMQ 3.6, but our image uses 3.5. Should I use this alternate download: https://bintray.com/rabbitmq/community-plugins/rabbitmq_delayed_message_exchange/v3.5.x#files ?

**Comment by fancyremarker** [comment]
@krallin : yes, exactly — thanks for catching that and implementing as such in #16.
