### ISSUE TITLE
Expose the RabbitMQ management plugin interface

### ISSUE THREAD

**Issue by chasballew** [aptible/docker-rabbitmq#9]
Per [RabbitMQ](https://www.rabbitmq.com/management.html):

> The rabbitmq-management plugin provides an HTTP-based API for management and monitoring of your RabbitMQ server, along with a browser-based UI and a command line tool, rabbitmqadmin.

Customers would like to be able to use this plugin on Aptible. I believe this is currently not feasible because we only expose one port per container right now.

cc @cilindrox

**Comment by lumberj** [comment]
What's the status on this?

**Comment by krallin** [comment]
Looks like we never closed this issue; this is supported as of January this year : https://www.aptible.com/blog/rabbitmq-management/
